### ISSUE TITLE
Increment the Docker image version via GitHub Action

### ISSUE THREAD

**Issue by infotexture** [dita-ot/dita-ot-action#5]
## Description

So far, @jason-fox has bumped the DITA-OT version in the [dita-ot-action/Dockerfile](https://github.com/dita-ot/dita-ot-action/blob/master/Dockerfile#L6) manually after each release, but since we were all busy at [DITA-OT Day](https://www.oxygenxml.com/events/2022/dita-ot_day.html), we missed that step for the 4.0 release.

The Docker image currently uses [3.7.4](https://github.com/dita-ot/dita-ot-action/blob/master/Dockerfile#L6): 

```docker
FROM ghcr.io/dita-ot/dita-ot:3.7.4 AS DITA_OT
```

## Possible Solution

Could we automate this process as part of the normal DITA-OT release process?

I realize there may be a bit of a chicken-and-egg problem here, as the release may need to be published before this change can (or should) be made, but if the action code would at least generate a PR automatically, we could wait to merge the PR until the release has been published.

**Comment by jason-fox** [comment]
If `dita-ot/dita-ot` has a tag xxxx, then the following command will edit the `Dockerfile` over here in `dita-ot/dita-ot-action`

```console
sed -E  's/([0-9]{1,}.){1,}([0-9]){1,}/xxxx/g' Dockerfile  > Dockerfile.tmp && mv Dockerfile.tmp Dockerfile
```
